### ISSUE TITLE
Thoughts and feedback

### ISSUE THREAD

**Issue by on3iro** [zzorba/ArkhamCards#65] opened 2020-08-17 09:21 UTC
Hey guys,

I really love your amazing app and decided to create this as some kind of "collection" issue containing all my feedback, thoughts and questions I have for **arkham cards**. 

The reason for me to do this, is because I would like to discuss a few topics with you before they might be split out into actual actionable issues. I would also be interested in directly contributing on some of them. (However I am currently rather busy, so I probably won't be able to start working on issues until the end of september/early october).

Now to the actual feedback ;)

### "Build physical deck" support
I would love to have a feature supporting me to build my actual physical deck.
I imagine some kind of separate list (maybe reachable trough the right hand burger menu, like weaknesses are). 
The list should be rather simple:

* cards should be checkable, so that I know I already collected them from my physical storage solution
* cards should be sortable by various conditions (like on arkhamdb), e.g. by cycle and number

If adding another list like this would be overkill, maybe we could add a way to show the card number inside the "Edit Deck" view. That way we could use the existing sorting to find cards by cicle and number as an easy fix.

> (We store all our player cards in binders and sorted by cycle and number. Currently we have to click on each and every card, to see its number in its respective cycle, which is a bit cumbersome)

### Add a way to manually add campaign notes/assets
We had a situation where we somehow misclicked something and accidentaly did not add a campaign asset to an investigators deck (can't remember exactly what it was, but iirc it  was in the dunwich cycle).
We just realized this later in the campaign, when the respective entry in the campaign log was missing (our deck still had the item though...).

The only way to fix this was, to create a new campaign and re-trace all decisions we made and then add the card correctly.

It would be great, if there was an advanced view of the campaign log, showing all decisions by scenario and a way to change these decisions/add log entries. (without breaking the internal logic of a cycle of course - so only valid selections should be possible).

## Bugs & UX
* Searching cards while deckbuilding is really slow, I wonder if this is because the actual filtering is rather sophisticated (considering that it accounts for deckbuilding restrictions etc.). But maybe there is a way to make this faster and more responsive?
* When upgrading decks there is a temporary state mismatch between the cards inside the deck and the list of card changes. Example: I have 2x OB of Lore and remove one, the change is correctly being reflected inside the actual deck, but if I click the card inside the change list, the element for adding/removing cards, still shows, that I have two in there
* As a first time user it is not immediately clear, that changing the language (of course) needs a data refetch. However if I change the language and accidentaly clicked the wrong one and want to change it back, I am not able to do so until  I switched to another tab (where the data fetching starts). There's two things I would do here:
    1. Don't block the language switch, until the user actually switches to a tab where the data fetching starts
    2. Make it more obvious, that some form of data re-fetching is going to happen (maybe add an additional note)

**Comment by zzorba** [comment] 2020-08-17 14:33
Thanks for writing in.  

First of all, love the idea of the physical checklist, and I don't think it would be too hard to implement. Might see if I can squeeze that in in the coming weeks as a 'simple' little addition.

As far as editing campaign log entries, I did finally crack a way to allow for edits between scenarios (hasn't been released yet, but I now let you adjust investigator trauma between scenarios from the main screen). It's possible something similar could be done with campaign logs -- the problem is the campaign log entries that change the effects. The campaign is setup in a very 'linear' fashion right now, since basically every piece of campaign/investigator state (trauma/cards/etc) can change the branching. So it basically starts at the beginning, and runs through the (dynamic) paths, updating the state as it goes. Changing an old decision is theoretically possible in such a system, however it might invalidate future decisions in a way that is hard to know.  That's why I've basically only provided an undo button at all time, but not a change past decision button (but I agree its unsatisfying if you change it at the wrong place). My main fear is that not all the paths are complete, i.e. in Forgotten Age or Dream Eaters it might use the presence of tokens to know what the past decision was -- if suddenly those stop making sense it could lead to a dead-end in the campaign log. An 'unwind to this point in the campaign' could probably be accomplished.


**Bugs**
- Yeah, I need to redo that search. I recently had to move database providers to unlock the hermes engine (which was a big speedup on android), however it seems like the new one no longer caches partial queries. I assume the 'slow' part is doing text search for cards -- I think I should probably reimplement that to just do local text processing rather than rely on the database. I'll see about making that change.
- That upgrade bug has plagued me for a while, I'll get it fixed, thanks for reminding me.
- I'll add a confirmation box to the language picker, since yes -- it's quite a slow operation.

**Comment by on3iro** [comment] 2020-08-17 15:24
thanks for the quick and detailed response :) It's awesome that you seem to have all major issues we have got already on your radar. And it's even more awesome, that you consider the physical checklist :D.

Just let me know if I can support you with anything in the future or if you have any remaining questions regarding my feedback. I would be glad to help out every now and then.
(if you do not want any contributions, that's also fine, of course).

**Comment by zzorba** [comment] 2020-08-17 15:49
Actually just pushed the fix for that upgrade thing, turns out it was a one-liner 👍 

Absolutely welcome contributions (the digital chaos bag + odds calculators were originally contributed). I might also be starting on a simple website/backend to allow for campaign sharing + collaboration in the next couple months, if that sort of development is more interesting than react-native.

Let me know when you're free / if you want to bounce an idea for a contribution off me -- you can always reach out by email via the contact link in the app.

**Comment by zzorba** [comment] 2020-08-19 16:48
The bug/UX issues should be addressed in the upcoming release (2.5.4, just went live on Apple and on the beta branch in Android).

I'll look into the checklist mode next.

**Comment by on3iro** [comment] 2020-08-20 05:37
That's awesome! Thanks for all of your work :+1:

**Comment by on3iro** [comment] 2020-11-10 20:09
@zzorba didn't play in quite some time and just opened up the app again - wow, amazing progress. I really like the new design and you even did implement the checklist feature 🎉 Awesome, thanks a lot!

One minor thing I just encountered: when I upgrade a card by touching the up arrow in the decklist, it loads quite a long time. I don't know if that can be mitigated, but if not a loading spinner would probably be helpful to give the user feedback, that something is indeed happening :)

**Comment by zzorba** [comment] 2020-11-10 20:59
Thank you for reporting that delay -- seems to be an android specific issue, something off with my touchable library.  Will try to get that fixed (it should be instantaneous).

**Comment by on3iro** [comment] 2020-11-19 18:25
@zzorba yeah, on android the performance seems to be pretty bad at the moment (at least for me and my girlfriend). Whenever we touch a card/investigator or press the add/subtract buttons it loads quite a long time without any visible response. Swiping between cards works fine, though.

**Comment by zzorba** [comment] 2020-11-19 20:44
Yeah, unfortunately the android simulator is basically unusable, making it next to impossible to debug any of these issues without a physical device (which I don't have).

 I'll see what can be done to speed things up.

**Comment by on3iro** [comment] 2020-11-21 14:14
While I don't have much time right now, I might be able to help out. I will try to set up the project on my local machine over the next couple of days and try to debug the issue with my android phone.

**Comment by zzorba** [comment] 2020-11-21 16:25
I think the new version (2.8.10, published today), should be much faster on the edits stream. There’s still some big differences between iOS and Android, but some testers have said anecdotally that it seems faster

**Comment by on3iro** [comment] 2020-11-22 08:44
@zzorba yeah I can confirm that - great job. It definitely feels a lot better now :+1: The UX is still  a little sluggish sometimes, because the user does get no immediate feedback upon touching certain parts (e.g. the level 0/level 1-5 filtering). But in general the app feels really usable again. Before this update it was almost unusable on android (at least for us).

Thanks for the quick fix :)

**Closed** 2021-03-09 08:20 UTC
